### ISSUE TITLE
Goals of the project [Question]

### ISSUE THREAD

**Issue by norman784** [elect86/uno-sdk#1]
I'm curious about the goals of the project, more about if in the future it will support other than JVM or at least if its planned.

I know that right now Kotlin native its not worth it, so if later on the project could migrate in some way to support both JVM and Native.

Btw according to their blog [Kotlin 1.2](https://blog.jetbrains.com/kotlin/2017/10/kotlin-1-2-beta2-is-out/) will support multi-platform projects.

Regards

**Comment by elect86** [comment]
Goals of the project is essentially to have a unique lib that brings all the features you need to develop in OpenGL, such as glm, gli, gln, buffer helpers, etc..

No plan yet, but I guess it'd be cool to think about that, if you are willing to try or want offer any sort of collaboration please don't hesitate and jump in :)

**Comment by norman784** [comment]
I'm waiting right now to Kotlin native be more stable and usable, but will se cool also to think ahead time and try to structure for future native implementations.

Well, when 1.2 rolls out I look again here to start playing around multi-platform implementation :)

**Comment by elect86** [comment]
I'll close this for now

Fell free to open it again if needed
